[package]
name = "or2-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rand.workspace = true
russh.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
zeroize.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync"] }
