package io.github.code_akram.or2.about

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Parses the real assets under `src/main/assets/licenses/` (generated by `scripts/gen-licenses.sh`),
 * so a generator change that the app cannot read fails here, and checks every listed licence has a
 * GPL-3.0-compatible alternative.
 */
class LicenseDataTest {
    private val assets = File("src/main/assets")

    private fun read(path: String) = File(assets, path).readText()

    private val data by lazy { LicenseData.load(::read) }

    @Test
    fun theRustListHoldsTheLinkedCratesAndTheZigBuiltComponents() {
        val names = data.rust.map { it.name }
        for (known in listOf("russh", "tokio", "uniffi", "libghostty-vt", "aws-lc-sys", "Ghostty (libghostty-vt)", "Rust standard library")) {
            assertTrue("$known missing from the Rust list", known in names)
        }
        assertTrue("only ${data.rust.size} Rust entries", data.rust.size > 150)
        val ghostty = data.rust.single { it.name == "Ghostty (libghostty-vt)" }
        assertEquals("MIT", ghostty.license)
        assertTrue(ghostty.version.contains("22d13172cde9"))
        assertTrue(ghostty.texts.single().body.contains("Mitchell Hashimoto"))
        // Dev-only and build-only crates are not shipped, so they are not listed.
        assertFalse("uniffi_bindgen" in names)
        assertFalse("cc" in names)
    }

    @Test
    fun theAndroidListHoldsTheReleaseRuntimeClasspath() {
        val names = data.android.map { it.name }
        for (known in listOf("androidx.room:room-runtime", "androidx.biometric:biometric", "net.java.dev.jna:jna", "org.jetbrains.kotlin:kotlin-stdlib")) {
            assertTrue("$known missing from the Android list", known in names)
        }
        // Test-only artifacts never reach the release classpath.
        assertFalse("junit:junit" in names)
        assertFalse("org.xerial:sqlite-jdbc" in names)
        val jna = data.android.single { it.name == "net.java.dev.jna:jna" }
        assertEquals("LGPL-2.1-or-later OR Apache-2.0", jna.license)
        assertEquals("jna", jna.displayName)
    }

    @Test
    fun theVendoredListComesFromTheNoticesTable() {
        assertEquals(
            listOf("Gradle 8.13", "herdr 0.9.3 API schema", "Catppuccin Mocha", "mosh-rs"),
            data.vendored.map { it.name },
        )
        val mosh = data.vendored.single { it.name == "mosh-rs" }
        assertEquals("GPL-3.0-or-later", mosh.license)
        assertEquals("90b3712", mosh.version)
        assertEquals("https://github.com/wilsonglasser/mosh-rs", mosh.repository)
        assertTrue(mosh.details!!.contains("Wilson Glasser"))
        assertTrue(mosh.texts.single().body.contains("GNU GENERAL PUBLIC LICENSE"))
        val catppuccin = data.vendored.single { it.name == "Catppuccin Mocha" }
        assertTrue(catppuccin.texts.single().body.contains("Copyright (c) 2021 Catppuccin"))
        assertTrue(data.vendored.single { it.name == "Gradle 8.13" }.texts.single().body.contains("Apache License"))
    }

    @Test
    fun appLicenseTextIsTheFullGpl() {
        assertTrue(data.gpl.startsWith("                    GNU GENERAL PUBLIC LICENSE") || data.gpl.contains("GNU GENERAL PUBLIC LICENSE"))
        assertTrue(data.gpl.contains("Version 3, 29 June 2007"))
        assertEquals(File("../../LICENSE").readText(), data.gpl)
    }

    @Test
    fun everyEntryHasANameALicenceAndNonEmptyText() {
        for (group in LicenseGroup.entries) {
            val entries = data.group(group)
            assertTrue("$group is empty", entries.isNotEmpty())
            assertEquals("duplicate keys in $group", entries.size, entries.map { it.key }.toSet().size)
            for (entry in entries) {
                assertTrue("${entry.key} has no name", entry.name.isNotBlank())
                assertTrue("${entry.key} has no licence", entry.license.isNotBlank())
                assertTrue("${entry.key} has no text", entry.texts.isNotEmpty())
                entry.texts.forEach { assertTrue("${entry.key} ${it.file} is empty", it.body.length > 10) }
                assertEquals(entry, data.find(entry.key))
            }
        }
    }

    @Test
    fun fallbackTextsAreFlaggedWithANote() {
        // A crate that ships no licence file is shown with the SPDX standard text and says so.
        val russh = data.rust.single { it.name == "russh" }
        assertNotNull(russh.note)
        assertTrue(russh.texts.single().file.endsWith("(standard text)"))
        assertEquals(null, data.rust.single { it.name == "tokio" }.note)
    }

    @Test
    fun noticesParserKeepsLinksAndPlainRows() {
        val markdown = """
            # Notices

            | Source | Commit | Path | Licence | Copyright |
            |---|---|---|---|---|
            | [Thing 1.0](https://example.invalid/thing) (extra words) | `0123456789abcdef` | `a/b.rs` | MIT; text in `LICENSE` | © 2020 Someone |
            | Plain name | n/a | `c` | Apache-2.0 | nobody |

            | Component | other |
        """.trimIndent()
        val standard = mapOf("MIT" to "MIT License\n\nCopyright (c) <year> <copyright holders>\n", "Apache-2.0" to "Apache text")
        val entries = LicenseParser.parseNotices(markdown, standard)
        assertEquals(listOf("Thing 1.0", "Plain name"), entries.map { it.name })
        assertEquals("MIT", entries[0].license)
        assertEquals("0123456", entries[0].version)
        assertEquals("https://example.invalid/thing", entries[0].repository)
        assertEquals("Copyright (c) 2020 Someone", entries[0].texts.single().body.lines()[2])
        assertEquals("", entries[1].version)
        assertEquals("Apache text", entries[1].texts.single().body)
        assertTrue(entries[0].details!!.contains("Source: Thing 1.0 (https://example.invalid/thing) (extra words)"))
    }

    @Test
    fun summaryLinesJoinVersionAndLicence() {
        val entry = LicenseEntry(LicenseGroup.Rust, "x", "1.2.3", "MIT OR Apache-2.0", "", emptyList())
        assertEquals("1.2.3 · MIT OR Apache-2.0", entry.summary)
        assertEquals("MIT", entry.copy(version = "", license = "MIT").summary)
    }

    // --- GPL-3.0 compatibility of everything listed ------------------------------------------

    /** SPDX ids that may be combined into a GPL-3.0-or-later work. */
    private val compatible = setOf(
        "MIT", "MIT-0", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "0BSD", "Unlicense", "Zlib", "MPL-2.0",
        "Unicode-3.0", "LGPL-2.1-or-later", "GPL-3.0-or-later", "CC0-1.0", "BSL-1.0",
    )

    /** An SPDX expression is usable when one alternative of each OR holds; `WITH` exceptions only widen a licence. */
    private fun usable(expression: String): Boolean {
        val tokens = Regex("""\(|\)|[^\s()]+""").findAll(expression.replace("/", " OR ")).map { it.value }.toList()
        return Expression(tokens).parse()
    }

    private inner class Expression(private val tokens: List<String>) {
        private var pos = 0

        fun parse(): Boolean = or().also { check(pos == tokens.size) { "unparsed tail in $tokens" } }

        private fun peek() = tokens.getOrNull(pos)

        private fun atom(): Boolean {
            val token = tokens[pos++]
            if (token == "(") return or().also { check(tokens[pos++] == ")") }
            if (peek() == "WITH") pos += 2
            return token in compatible
        }

        private fun and(): Boolean {
            var result = atom()
            while (peek() == "AND") { pos++; result = atom() && result }
            return result
        }

        private fun or(): Boolean {
            var result = and()
            while (peek() == "OR") { pos++; result = and() || result }
            return result
        }
    }

    @Test
    fun everyListedLicenceHasAGplCompatibleAlternative() {
        val incompatible = (data.rust + data.android).filterNot { usable(it.license) }.map { "${it.name} ${it.license}" }
        assertEquals("licences not known to be GPL-3.0-compatible", emptyList<String>(), incompatible)
        assertTrue(usable("(MIT OR Apache-2.0) AND Unicode-3.0"))
        assertTrue(usable("ISC AND (Apache-2.0 OR ISC)"))
        assertFalse(usable("GPL-2.0-only"))
        assertFalse(usable("MIT AND SSPL-1.0"))
        assertTrue(usable("Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"))
    }
}
